version: "3.1"

name: "db-scuffle-dev"

services:
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  pgadmin:
    image: dpage/pgadmin4:6.20
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json

networks:
  default:
    name: scuffle-dev
    external: true
